services:
  discordbot:
    image: ghcr.io/avinho/discordbot:latest
    container_name: discordbot
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    volumes:
      - ~/.ssh:/home/ubuntu/.ssh:ro
    env_file:
      - .env
    restart: unless-stopped