services:
  discordbot:
    build: .
    container_name: discordbot
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
    volumes:
      - /var/run/screen:/var/run/screen
    env_file:
      - .env
    restart: unless-stopped